# Generated by Django 3.0.14 on 2024-11-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter_id', 'candidate')},
        ),
    ]
